name: saferoute
description: Custom Path Navigator - Create and follow custom safe routes
publish_to: "none"
version: 1.0.0+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.3.0
  location: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2
  permission_handler: ^12.0.0+1
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.1.10
  qr_flutter: ^4.1.0
  fluentui_system_icons: ^1.1.273
  supa_carbon_icons: ^0.0.1+6
  json_serializable: ^6.9.0
  apple_maps_flutter: ^1.4.0
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  riverpod: ^2.6.1
  provider: ^6.1.4
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  get_it: ^8.0.3
  injectable: ^2.5.0
  injectable_generator: ^2.6.2
  toastification: ^1.0.0
  qr_code_scanner:
    path: ../../thanhtunguet/qr_code_scanner
    # git:
    #   url: https://github.com/thanhtunguet/qr_code_scanner.git
    #   ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.15
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
